# Generated by Django 5.1 on 2024-08-26 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_name', models.CharField(db_comment='chatroom name', max_length=255, unique=True)),
                ('avatar_url', models.URLField(db_comment='avatar url of chatroom', default='')),
                ('room_type', models.CharField(choices=[(1, 'Single'), (2, 'Group'), (3, 'Official')], db_comment='type of chatroom', default=1, max_length=10)),
                ('last_message_timestamp', models.BigIntegerField(db_comment='the last message of created at timestmap', default=0, null=True)),
            ],
            options={
                'db_table': 'chatrooms',
                'db_table_comment': 'chatroom data',
            },
        ),
        migrations.CreateModel(
            name='ChatroomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leaved_at', models.DateTimeField(null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='chat.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'db_table': 'chatroom_members',
                'db_table_comment': 'member data in the chatroom',
            },
        ),
    ]
