# Generated by Django 5.1 on 2024-08-26 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(db_comment='username', default='', max_length=255)),
                ('email_address', models.EmailField(db_comment='email address', db_index=True, max_length=255, unique=True)),
                ('user_type', models.CharField(choices=[(1, 'Common'), (2, 'Official')], db_comment='type of user', default=1, max_length=10)),
                ('avatar_url', models.URLField(db_comment='url of user avatar', default='')),
                ('is_disabled', models.BooleanField(db_comment='status of user was not actived', default=False)),
                ('disabled_at', models.DateTimeField(db_comment='the datetime of user was not actived', null=True)),
            ],
            options={
                'db_table': 'users',
                'db_table_comment': 'user data',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='READY', max_length=255)),
                ('sent_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='account.user')),
            ],
            options={
                'db_table': 'emails',
                'db_table_comment': 'email data',
            },
        ),
    ]
